IMAGE_PATH = "test_images/branos.png"
RESIZE = 64
NUM_COMPUTE_NODES = 1024
NUM_OUTPUT_NODES = 8
POSITION_ENCODING_DIM = 128
HIDDEN_DIM = 256
RECURRENT_DIM = 128
NUM_LAYERS = 4

NUM_PERTURBATIONS = 128
PERTURBATION_SIZE = 1e-4
STEP_SIZE = PERTURBATION_SIZE / 2
NUM_PRIOR_GATES_CONNECTABLE = NUM_COMPUTE_NODES // 16
